on:
  push:
    branches: [ develop ]
#   pull_request:
#     branches: [ develop ]

name: (Develop Server) Deploy Spring boot to Amazon EC2
env:
  PROJECT_NAME: be-admin_spring-boot

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_DEVELOP_IAM_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_DEVELOP_IAM_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://goodsduck-admin/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name be-admin_spring-boot --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name be-admin_spring-boot_group --s3-location bucket=goodsduck-admin,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
